/*
 * trilocfg.c - Native key storage with obfuscation
 *
 * This is the TEMPLATE file. The actual C code is generated by
 * native_build.py with injected key fragments, encrypted strings,
 * and 8 layers of obfuscation.
 *
 * Layers:
 *   1. String encryption (XOR)
 *   2. Dynamic symbol resolution (dlopen/dlsym)
 *   3. Key fragmentation (16 bytes, mixed obfuscation)
 *   4. Control flow flattening (switch dispatcher)
 *   5. Anti-debug (ptrace + TracerPid)
 *   6. Anti-emulator (QEMU detection)
 *   7. Code integrity (.text CRC32)
 *   8. Timing detection (clock_gettime sampling)
 */

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <sys/syscall.h>

/* Minimal JNI types to avoid jni.h symbol exposure */
typedef void*   JNIEnv;
typedef void*   jclass;
typedef void*   jbyteArray;
typedef int8_t  jbyte;
typedef int32_t jint;

/* ─── JNI_OnLoad ─── */
JNIEXPORT jint JNI_OnLoad(void *vm, void *reserved) {
    (void)vm;
    (void)reserved;
    return 0x00010006;  /* JNI_VERSION_1_6 */
}

/*
 * The actual obfuscated code is generated by native_build.py.
 * See the _generate_obfuscated_c() function for details.
 *
 * Key points:
 * - Key fragments are XOR/ADD/ROL encoded, scattered across functions
 * - All strings are XOR-encrypted
 * - Anti-debug checks return fake key if debugger detected
 * - Control flow is flattened into a switch state machine
 */
